services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
#      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
#      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=patientdb
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: